apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: cicd-demo-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cicd-demo-deployment
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50